export const INIT_LAUNCH_CALENDAR = 'SET_LAUNCH_CALENDAR';

export const SHOW_FILTER_PANEL = 'SHOW_FILTER_PANEL';

export const NEXT = 'NEXT';

export const PREV = 'PREV';

export const INIT_DAYS = 'INIT_DAYS';

export const INIT_AGENCIES = 'INIT_AGENCIES';

export const SET_SELECTED_AGENCIES = 'SET_SELECTED_AGENCIES';

export const SET_SLIDE_INDEX = 'SET_SLIDE_INDEX';

export const SET_FILTERED_DAYS = 'SET_FILTERED_DAYS';
